### PR TITLE
Maodify actions.xml

### PR DESCRIPTION
**Pull request by richosad**
Added Actions for setInput

### CODE REVIEW

**Comment by discgolfer1138** [comment]
if your previous pull request depends on these changes to actions.xml, please include those changes in that pull request and close this one.. thanks.

**Comment by richosad** [comment]
OK 
It’s the first time I’m using GitHub so I’m learning ;-)

Ryszard Sadowski
rsadowski@mac.com

**Comment by discgolfer1138** [comment]
no problem at all :) I appreciate your help!

**Comment by richosad** [comment]
I will pull off the requests and do them again

Ryszard Sadowski
rsadowski@mac.com

**Comment by richosad** [comment]
Should I just send the lines that I have changed/added?

Ryszard Sadowski
rsadowski@mac.com

**Pull request closed without merging**
